@token= eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0MH0.R3HIHcuV6r_9gx6OgJgau1iaE1N980-L9bwr_KBlcSM

# GET ALL
GET http://192.168.64.5:3000/tasks.json
Authorization: Bearer {{token}}

### CREATE TASK

@test=9
POST http://192.168.64.5:3000/tasks.json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "description": "test {{test}}"
}

### UPDATE 

PUT http://192.168.64.5:3000/tasks/23.json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "task" : {
    "description": "edited with token"
    }
}

### DELETE TASK
 
DELETE http://192.168.64.5:3000/tasks/23.json
Authorization: Bearer {{token}}

